### ISSUE TITLE
Speed up with OpenMP and OpenCL

### ISSUE THREAD

**Issue by CGLemon** [AkkyOrz/3D_CA#1]
The three dimension life game is vary beautiful. But this is a littel slow in bigger grid. 
I added OpenMp and  OpenCL to speed up.
This is significant improved with OpenMp and OpenCL.
And compiling the codes with clang is better.

Here is the codes.
https://github.com/CGLemon/3D_CA

**Comment by AkkyOrz** [comment]
Thank you for your improvement and your advice.
I want to merge your commit.

**Comment by CGLemon** [comment]
Thanks a lot. But some bugs exist. I fixed it already and uploaded them.
